version: 3.0.0.{build}-beta
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    powershell .\build.ps1 -Verbosity diagnostic
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
